### PR TITLE
Update to version 0.8.3

### PR DESCRIPTION
**Pull request by vitimiti**
Updated all files and sha256 sum checks to release 0.8.3 for parity with the official Pixelorama releases.

### CODE REVIEW

**Comment by vitimiti** [comment]
image

This version is core dumping on Linux, I'd suggest waiting until there is a working version, unfortunately.

**Comment by Technohacker** [comment]
I tried building this with `org.godotengine.godot.BaseApp/x86_64/3.3` as the base, it seems to work fine now. Maybe we could have this tested again and updated?

**Comment by vitimiti** [comment]
I have reopened to start retesting on this version as requested.

**Comment by vitimiti** [comment]
I think I am messing something up in my installation process and I'm not sure what. This affects stable as well, so I know it is my fault. If somebody that has more brain cells than me could test this? It is building and installing, it should work if I wasn't installing it incorrectly.

**Comment by vitimiti** [comment]
Ah, it does in fact not work as it is right now. Stable does, it is this branch that doesn't:
Screenshot_20210801_084154

**Comment by vitimiti** [comment]
So I am testing the original tar, and it does work on my machine with 0 problems, it seems to be more a problem with how the flatpak is being built. @Technohacker you have commented that you are getting it to work by using a different baseapp for Godot, but I am unaware of how to configure that with the files I have at hand from this repository. Can you elaborate/help with that?
Screenshot_20210801_090415

**Comment by vitimiti** [comment]
Well, I figured it out, sorry, I still stress out with yaml files, not used to them. Let me test this again and will come back with it.

**Comment by vitimiti** [comment]
And it does work, this should be valid for stable branches to get the version 0.8.3. And I have learnt where the base app is and how to update it for the next time this happens, thank you.
Screenshot_20210801_091425
Screenshot_20210801_091445

**Comment by Technohacker** [comment]
Ah sorry, I wasn't able to check in the past hour :sweat_smile: 
Glad to know it's fixed now! :D

**Comment by Calinou** [comment]
PS: I'm updating the Godot BaseApp to 3.3.2: https://github.com/flathub/org.godotengine.godot.BaseApp/pull/12

**Comment by OverloadedOrama** [comment]
Superseded by #11, which upgrades Pixelorama to 0.9

**Pull request closed without merging**
