### PR TITLE
Update to Pixelorama 0.9

### PR DESCRIPTION
**Pull request by OverloadedOrama**
Supersedes #10

### CODE REVIEW

**Comment by Calinou** [comment]
The app fails to run:

```
❯ com.orama_interactive.Pixelorama
/app/bin/godot-runner: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/bin/godot-runner)
/app/bin/godot-runner: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /app/bin/godot-runner)
```

**Comment by Calinou** [comment]
The app fails to run after being installed with the above command:

```
❯ com.orama_interactive.Pixelorama                                                                             
/app/bin/godot-runner: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app/bin/godot-runner)
/app/bin/godot-runner: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /app/bin/godot-runner)
```

This does not occur with the current stable version on Flathub. I have no idea why…

**Comment by OverloadedOrama** [comment]
I'm having the same issue on Pop!_OS 21.04. The stable version from Flathub seems to be working for me too.

**Comment by OverloadedOrama** [comment]
I'm not sure if this is the problem, but maybe the runtime-version should be 21.08 instead of 20.08? I noticed that org.godotengine.godot.BaseApp 3.3 branch uses 21.08, while 3.2 uses 20.08.

**Comment by Calinou** [comment]
> I'm not sure if this is the problem, but maybe the runtime-version should be 21.08 instead of 20.08? I noticed that org.godotengine.godot.BaseApp 3.3 branch uses 21.08, while 3.2 uses 20.08.

Indeed, the runtime should be updated to 21.08 in this PR.

**Comment by OverloadedOrama** [comment]
It seems to run fine now.

**Comment by Calinou** [comment]
I tested it again, it works fine here too :slightly_smiling_face: 

image

**Review by Calinou — APPROVED** [review]
Thanks!

**Pull request merged**
