### PR TITLE
Update to v0.9.1

### PR DESCRIPTION
**Pull request by OverloadedOrama**

### CODE REVIEW

**Comment by OverloadedOrama** [comment]
I think the issue might be that [this file](https://github.com/flathub/org.godotengine.godot.BaseApp/blob/branch/3.4/org.godotengine.godot.BaseApp.yaml) should say `branch: '3.4'` instead.

**Comment by hfiguiere** [comment]
yeah filed the issue for that.

**Comment by hfiguiere** [comment]
pushed a fix

**Comment by hfiguiere** [comment]
you need to wait that it builds.

**Comment by OverloadedOrama** [comment]
Still failing. Hasn't Godot finished building yet?

**Comment by hfiguiere** [comment]
still not published. even though I published it. there are delays involved that I don't control.

**Comment by OverloadedOrama** [comment]
Ah okay, sorry. I saw the "all checks have passed" in org.godotengine.godot.BaseApp and thought it was ready. I'll try again tomorrow then. Thanks for the help!

**Comment by hfiguiere** [comment]
bot, build

**Comment by hfiguiere** [comment]
I'll let you finish this. build did finish successfully.

**Comment by OverloadedOrama** [comment]
Thank you for your help! :)

**Pull request merged**
